import * as React from "react";
import Head from "next/head";
import { LayoutProps } from "./types";
import { useTranslation } from "react-i18next";

const Layout = (props: LayoutProps) => {
  const { title = "", children } = props;
  const { t } = useTranslation();

  return (
    <div>
      <Head>
        <title>{t(title)}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
    </div>
  );
};

export default Layout;
