import * as React from "react";
import Head from "next/head";
import { LayoutProps } from "./types";

const Layout = (props: LayoutProps) => {
  const { title, children } = props;

  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
    </div>
  );
};

export default Layout;
