import * as React from "react";
import Head from "next/head";

const Layout = (props: { children: any }) => {
    const { children } = props;

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {children}
        </div>
    );
};

export default Layout;
